language: android

env:
  global:
    - API_LEVEL_ANDROID=25
    - API_LEVEL_EMULATOR=23
    - BUILD_TOOLS=25.0.0
    - ADB_INSTALL_TIMEOUT=20
    - ANDROID_ABI=armeabi-v7a

jdk:
  - oraclejdk8
    
before_install:
  - chmod +x gradlew
 
android:
  components:
    - tools
    - platform-tools
    - build-tools-$BUILD_TOOLS
    - android-$API_LEVEL_ANDROID
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android-$API_LEVEL_ANDROID
    - sys-img-armeabi-v7a-android-$API_LEVEL_EMULATOR

before_script:
  - echo no | android create avd --force -n test -t "android-"$API_LEVEL_EMULATOR --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
    
script:
  - ./gradlew clean build connectedCheck --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)
