language: android
jdk:
    - oraclejdk8
android:
  components:
    - platform-tools
    - tools

    # The build tools version used by your project
    - build-tools-25.0.0

    # The SDK version used to compile your project
    - android-25
    
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
    - chmod +x gradlew
    
script:
    - ./gradlew build connectedCheck